### ISSUE TITLE
Unable to add a User to a Team with a particular Role

### ISSUE THREAD

**Issue by gurchik** [kmart2234/node-pagerduty#16]
For adding a User to a Team, [the PagerDuty API Reference](https://api-reference.pagerduty.com/#!/Teams/put_teams_id_users_user_id) specifies an optional parameter, `role`, with the description `Can be observer, responder or manager`. However, there isn't a way currently to define this using this API:

https://github.com/kmart2234/node-pagerduty/blob/master/lib/pd.js#L861

**Comment by gurchik** [comment]
This should be an easy fix so I'm more than happy to pick this up if you wish.

**Comment by kmart2234** [comment]
Thanks for catching this Derek. I am working on a release right now to add methods that are not currently available. I will also add this to that release.

**Comment by kmart2234** [comment]
This should now be resolved as well.
