### ISSUE TITLE
Unable to search for users on a team

### ISSUE THREAD

**Issue by gurchik** [kmart2234/node-pagerduty#17]
According to the [API Reference](https://api-reference.pagerduty.com/#!/Teams/get_teams_id_members) there is a way to get a list of users on a team. But this functionality is not yet exposed by this module, only [adding and removing](https://github.com/kmart2234/node-pagerduty/blob/master/lib/pd.js#L853) users from a team.

**Comment by gurchik** [comment]
Since this fix should be easy, I'd be happy to pick this up if you'd like. Just let me know!

**Comment by kmart2234** [comment]
v1.2.0 fixes this issue.
