### ISSUE TITLE
sendEvent() does not check for error responses

### ISSUE THREAD

**Issue by mearns** [kmart2234/node-pagerduty#6]
When a request is made to the Pagerduty API with the `Client.prototype.events.sendEvent` method, and the request fails, at least in some cases, the method still returns a promise that fulfills, seeming to indicate success. In one instance, I sent a badly formed event and pagerduty sent back a 400 response indicating the error. In my opinion, the `sendEvent` method should have given me a Promise that rejected with some kind of error indicating the response, so I would know that my event had not been accepted.

There *is a workaround*, but it requires the calling code to inspect every response on their own, which is undesirable, imo.

I don't know if this is pervasive through out the package, but I would imagine it is. I also don't know what other errors it is masking in a similar way (e.g., if 5xx series responses would be treated any differently).

As a possible solution, if you use a library such as `axios` to make the requests, it will treat an error-indicating status codes as errors and return a promise that rejects.

**Comment by mearns** [comment]
Any feedback on this @kmart2234 ?

**Comment by kmart2234** [comment]
I plan to replace the request module with axios in version 2 of the module.

**Comment by mearns** [comment]
I see. Thanks
