### ISSUE TITLE
several npm warnings when installing ^1.1.0

### ISSUE THREAD

**Issue by softprops** [kmart2234/node-pagerduty#8]
given

```json
    "dependencies": {
        "node-pagerduty": "^1.1.0",
    }
```

I get warnings about a request library that is not installed by default which is a bit confusing

```
npm i
npm WARN request-promise-core@1.1.1 requires a peer of request@^2.34 but none is installed. You must install peer dependencies yourself.
npm WARN request-promise-native@1.0.5 requires a peer of request@^2.34 but none is installed. You must install peer dependencies yourself.
```

after manually adding `"request": "^2.88.0"` to my dependencies

I see the following warnings

```
found 8 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
```

most of these seem to relate to `node-pagerduty > request > hawk`

I'm newish to node dependency management. Are these warnings expected?

**Comment by kmart2234** [comment]
I will take a look at this.

**Comment by softprops** [comment]
verified in my project. thanks @kmart2234 !
